TASK_QUEUES = {
    'inspect_vector': 'vector',
    'inspect_pointcloud': 'point-cloud',
    'inspect_raster': 'vector',
    'inspect_photogrammetry': 'photogrammetry',
    'inspect_glb': 'mesh',
    'inspect_mesh': 'mesh',
    'create_polygon_3dtiles': 'vector',
    'create_point_instance_3dtiles': 'vector',
    'create_point_cloud_3dtiles': 'point-cloud',
    'create_mesh_3dtiles': 'mesh',
    'create_photogrammetry_3dtiles': 'photogrammetry',
    'complete_asset_remove_process': 'vector',
    'complete_pipeline_remove_process': 'vector',
}
