services:
  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production

  worker-vector:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  worker-point-cloud:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  worker-mesh:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
