name: Build frontend and backend, test and deploy

on:
  push:
    branches:
      - main
      - gha
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.copy .env

      - name: Build the docker images
        run: |
          DOCKER_BUILDKIT=1 docker compose \
            -f docker-compose.yml \
            -f docker-compose.worker.vector.yml \
            -f docker-compose.worker.point-cloud.yml \
            -f docker-compose.worker.mesh.yml \
            -f docker-compose.build.yml build \
            backend frontend worker-vector worker-point-cloud worker-mesh

      - name: Run tests
        run: sh scripts/test-local.sh

  login-and-deploy:
     runs-on: self-hosted
     needs: build-and-test
     if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.copy .env

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy the images
        run: |
          source .env
          docker push $DOCKER_IMAGE_BACKEND:$TAG
          docker push $DOCKER_IMAGE_FRONTEND:$TAG
          docker push $DOCKER_IMAGE_WORKER_VECTOR:$TAG
          docker push $DOCKER_IMAGE_WORKER_POINT_CLOUD:$TAG
          docker push $DOCKER_IMAGE_WORKER_MESH:$TAG
